spring.application.name=flowvisior
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:1337/flowvisior
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true